Mutation:
      type: object
      config:
          fields:
              singup:
                  type: "User"
                  resolve: "@=mutation('singup', [args])"
                  args:
                      input:
                          type: "UserInput"
              login:
                  type: "User"
                  resolve: "@=mutation('login', [args])"
                  args:
                      input:
                          type: "UserInput"
              projectCreate:
                  type: "Project"
                  resolve: "@=mutation('projectCreate', [args])"
                  args:
                      input:
                          type: "ProjectCreateInput"
              projectUpdate:
                  type: "Project"
                  resolve: "@=mutation('projectUpdate', [args])"
                  args:
                      input:
                          type: "ProjectUpdateInput"
              projectDelete:
                  type: "Project"
                  resolve: "@=mutation('projectDelete', [args])"
                  args:
                      input:
                          type: "ProjectInput"