UserInput:
    type: input-object
    config:
        fields:
            email:
                type: "String"
                description: "Email of User"
            password:
                type: "String"
                description: "Password of User"